2019-12-26 21:22:56,210 ERROR: Exception on /article [GET] [in c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Samuel\Desktop\pydasci\app\articles\routes.py", line 22, in article
    return render_template('auth/login.hmtl')
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: auth/login.hmtl
2019-12-26 21:23:16,747 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:77]
2019-12-26 21:23:54,236 ERROR: Exception on /article [GET] [in c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Samuel\Desktop\pydasci\app\articles\routes.py", line 22, in article
    return render_template('auth/login.html')
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\auth\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\base.html", line 41, in top-level template code
    {% block app_content %}{% endblock %}
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\auth\login.html", line 8, in block "app_content"
    {{ wtf.quick_form(form) }}
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\wtf.html", line 200, in template
    {{ form.hidden_tag() }}
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'form' is undefined
2019-12-26 21:24:12,536 ERROR: Exception on /article [GET] [in c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Samuel\Desktop\pydasci\app\articles\routes.py", line 22, in article
    return render_template('auth/login.html')
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\auth\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\base.html", line 41, in top-level template code
    {% block app_content %}{% endblock %}
  File "C:\Users\Samuel\Desktop\pydasci\app\templates\auth\login.html", line 8, in block "app_content"
    {{ wtf.quick_form(form) }}
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\runtime.py", line 574, in _invoke
    rv = self._func(*arguments)
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\wtf.html", line 200, in template
    {{ form.hidden_tag() }}
  File "c:\users\samuel\desktop\pydasci\venv\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
UndefinedError: 'form' is undefined
2019-12-26 21:28:02,664 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:77]
2019-12-26 22:09:35,375 INFO: Microblog startup [in C:\Users\Samuel\Desktop\pydasci\app\__init__.py:79]
